- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - "vars/perf.yml"
  tasks:
    
    

   
    #Create a security group for the ec2 instances that will form our ECS cluster
    - name: Create ECS security group
      tags: setup_sg
      ec2_group:
        name: "{{ cluster_name }}_ecs_sg"
        description: "Security Group for private subnet"
        vpc_id: "{{ vpc_id }}"
        state: present
        resource_tags:
          Name: "{{ cluster_name }}-ECS-sg"
        rules:
          - proto: tcp
            ports:
              - 22
            group_id: "{{ group_id }}"
            rule_desc: allow access on this host from jump server
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: ecs_sg
    - debug: var=ecs_sg verbosity=2


    - name: Delete MasspayPerf Auto-scaling group for ECS   
      tags: setup_ecs
      ec2_asg:
        name: "{{ cluster_name }}_ec2_asg"
        state: absent
        health_check_type: EC2
        default_cooldown: 300
        availability_zones:
          - "{{ vpc_region }}a"
          - "{{ vpc_region }}b"
        launch_config_name: "{{ cluster_name }}_ec2_lc"
        min_size: "{{ ec2_asg_min_size }}"
        max_size: "{{ ec2_asg_max_size }}"
        desired_capacity: "{{ ec2_asg_desired_capacity }}"
        vpc_zone_identifier:
          - "{{ pbl_subnet_a_id }}"
          - "{{ pbl_subnet_b_id }}"
        wait_for_instances: true
        tags:
          - Name: "{{ cluster_name }}_ec2_asg"
      register: ec2_asg
    - debug: var=ec2_asg verbosity=2

    - name: Delete ECS Launch Configuration
    #  when: update_all_components == true
      tags: setup_ecs
      ec2_lc:
        name: "{{ cluster_name }}_ec2_lc"
        state: "{{ ecs_state }}"
        image_id: "{{ ec2_ami_id }}"
        key_name: "{{ ec2_key_name }}"
        security_groups:
          - "{{ ecs_sg.group_id }}"
        instance_type: "{{ ec2_instance_type }}"
        instance_monitoring: true
        instance_profile_name: "ecsInstanceRole"
        assign_public_ip: false
        user_data: "#!/bin/bash\necho ECS_CLUSTER={{ cluster_name }} >> /etc/ecs/ecs.config"
      register: ec2_lc
    - debug: var=ec2_lc verbosity=2

   
    
    #Delete an ECS cluster for the application
    - name: Delete ECS cluster
      tags: setup_ecs
      ecs_cluster:
        name: "{{ cluster_name }}"
        state: "{{ ecs_state }}"
      register: ecs_cluster
    - debug: var=ecs_cluster verbosity=2


